const fs = require('fs');
const base = 'C:/Users/zrodr/Desktop/TRANSMETROLINEA/frontend';

const SIDEBAR = [
  '<aside class="sidebar" id="sidebar">',
  '  <div class="sidebar-logo">',
  '    <div class="logo-icon">&#x1F68C;</div>',
  '    <div class="logo-text"><h2>TRANSMETRO EN LINEA</h2><span>Sistema de Gestion</span></div>',
  '  </div>',
  '  <nav class="sidebar-nav">',
  '    <div class="nav-section">Principal</div>',
  '    <a class="nav-item" data-page="dashboard"><span class="nav-icon">&#x1F4CA;</span> Dashboard</a>',
  '    <div class="nav-section">Gestion</div>',
  '    <a class="nav-item" data-page="rutas"><span class="nav-icon">&#x1F6E3;&#xFE0F;</span> Rutas</a>',
  '    <a class="nav-item" data-page="unidades"><span class="nav-icon">&#x1F68C;</span> Unidades</a>',
  '    <a class="nav-item" data-page="conductores"><span class="nav-icon">&#x1F464;</span> Conductores</a>',
  '    <a class="nav-item" data-page="asignaciones"><span class="nav-icon">&#x1F517;</span> Asignaciones</a>',
  '    <div class="nav-section">Operaciones</div>',
  '    <a class="nav-item" data-page="monitoreo"><span class="nav-icon">&#x1F5FA;&#xFE0F;</span> Monitoreo GPS</a>',
  '    <a class="nav-item" data-page="reportes"><span class="nav-icon">&#x1F4C8;</span> Reportes</a>',
  '    <div class="nav-section">Admin</div>',
  '    <a class="nav-item" data-page="usuarios"><span class="nav-icon">&#x1F465;</span> Usuarios</a>',
  '  </nav>',
  '  <div class="sidebar-footer">',
  '    <div class="sidebar-user">',
  '      <div class="avatar" id="sidebarAvatar">A</div>',
  '      <div class="user-info"><strong id="sidebarName">Admin</strong><small id="sidebarRol">admin</small></div>',
  '    </div>',
  '    <button id="logoutBtn" class="btn btn-danger btn-sm" style="width:100%;margin-top:10px">Cerrar sesion</button>',
  '  </div>',
  '</aside>'
].join('\n');

function page(title, activePage, content, extraHead) {
  return [
    '<!DOCTYPE html><html lang="es"><head>',
    '<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>' + title + ' - Transmetro en Linea</title>',
    '<link rel="stylesheet" href="/css/styles.css">',
    (extraHead || ''),
    '</head><body>',
    SIDEBAR,
    '<div class="main-content">',
    '<div class="topbar">',
    '<div class="topbar-title">' + title + '</div>',
    '<div class="topbar-right"><div class="topbar-avatar" id="topbarAvatar">A</div></div>',
    '</div>',
    '<div class="page-content">',
    content,
    '</div></div>',
    '<script src="/js/api.js"></script>',
    '<script>setupSidebar("' + activePage + '")</script>',
    '</body></html>'
  ].join('\n');
}

// ===================== DASHBOARD =====================
const dashboardContent = [
  '<div class="page-header">',
  '  <div><h1>Panel Principal</h1><p>Resumen general del sistema</p></div>',
  '  <span id="fechaHora" style="color:#6b7280;font-size:13px"></span>',
  '</div>',
  '<div class="stats-grid">',
  '  <div class="stat-card"><div class="stat-icon azul">&#x1F68C;</div><div><div class="stat-value" id="stTotal">--</div><div class="stat-label">Total Unidades</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon verde">&#x2705;</div><div><div class="stat-value" id="stServicio">--</div><div class="stat-label">En Servicio</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon naranja">&#x1F527;</div><div><div class="stat-value" id="stMant">--</div><div class="stat-label">En Mantenimiento</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon rojo">&#x274C;</div><div><div class="stat-value" id="stFuera">--</div><div class="stat-label">Fuera de Servicio</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon verde">&#x1F6E3;&#xFE0F;</div><div><div class="stat-value" id="stRutas">--</div><div class="stat-label">Rutas Activas</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon azul">&#x1F464;</div><div><div class="stat-value" id="stConductores">--</div><div class="stat-label">Conductores Activos</div></div></div>',
  '</div>',
  '<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:20px">',
  '  <div class="card"><div class="card-header"><h3>Estado de Unidades</h3></div>',
  '    <div class="card-body" style="display:flex;align-items:center;justify-content:center;height:260px"><canvas id="chartUnidades" style="max-height:240px"></canvas></div></div>',
  '  <div class="card"><div class="card-header"><h3>Accesos Rapidos</h3></div>',
  '    <div class="card-body"><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">',
  '      <a href="/rutas.html" class="btn btn-primary" style="justify-content:center">Rutas</a>',
  '      <a href="/unidades.html" class="btn btn-success" style="justify-content:center">Unidades</a>',
  '      <a href="/conductores.html" class="btn btn-secondary" style="justify-content:center">Conductores</a>',
  '      <a href="/monitoreo.html" class="btn btn-outline" style="justify-content:center">Mapa GPS</a>',
  '      <a href="/asignaciones.html" class="btn btn-warning" style="justify-content:center;color:white">Asignaciones</a>',
  '      <a href="/reportes.html" class="btn btn-secondary" style="justify-content:center">Reportes</a>',
  '    </div></div></div>',
  '</div>',
  '<div class="card"><div class="card-header"><h3>Asignaciones Activas</h3></div>',
  '  <div class="card-body"><div class="table-wrap"><table>',
  '    <thead><tr><th>Unidad</th><th>Ruta</th><th>Conductor</th><th>Desde</th><th>Estado</th></tr></thead>',
  '    <tbody id="tbAsig"><tr><td colspan="5" class="loading"><div class="spinner"></div> Cargando...</td></tr></tbody>',
  '  </table></div></div></div>',
  '<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>',
  '<script>',
  'setInterval(function(){document.getElementById("fechaHora").textContent=new Date().toLocaleString("es-GT");},1000);',
  'async function loadStats(){',
  '  try{',
  '    var d=await api.get("/reportes/estadisticas");',
  '    document.getElementById("stTotal").textContent=d.unidades.total;',
  '    document.getElementById("stServicio").textContent=d.unidades.activas;',
  '    document.getElementById("stMant").textContent=d.unidades.mantenimiento;',
  '    document.getElementById("stFuera").textContent=d.unidades.inactivas;',
  '    document.getElementById("stRutas").textContent=d.rutas.activas;',
  '    document.getElementById("stConductores").textContent=d.conductores.activos;',
  '    new Chart(document.getElementById("chartUnidades"),{type:"doughnut",data:{labels:["En Servicio","Mantenimiento","Fuera"],datasets:[{data:[d.unidades.activas,d.unidades.mantenimiento,d.unidades.inactivas],backgroundColor:["#86ED5A","#f59e0b","#ef4444"],borderWidth:0}]},options:{cutout:"70%",plugins:{legend:{position:"bottom"}}}});',
  '  }catch(e){}',
  '}',
  'async function loadAsig(){',
  '  try{',
  '    var rows=await api.get("/asignaciones");',
  '    var activas=rows.filter(function(r){return r.estado==="activa";}).slice(0,8);',
  '    var tb=document.getElementById("tbAsig");',
  '    if(!activas.length){tb.innerHTML="<tr><td colspan=5 style=\'text-align:center;padding:20px;color:#9ca3af\'>Sin asignaciones activas</td></tr>";return;}',
  '    tb.innerHTML=activas.map(function(a){return "<tr><td><strong>"+a.unidad_numero+"</strong></td><td>"+a.ruta_nombre+"</td><td>"+a.conductor_nombre+" "+a.conductor_apellido+"</td><td>"+a.fecha_inicio+"</td><td><span class=\'badge badge-success\'>Activa</span></td></tr>";}).join("");',
  '  }catch(e){}',
  '}',
  'loadStats();loadAsig();',
  '</script>'
].join('\n');

fs.writeFileSync(base + '/dashboard.html', page('Dashboard', 'dashboard', dashboardContent, '<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>').replace('<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>\n</head>', '</head>'), 'utf8');
console.log('dashboard.html written');

// ===================== UNIDADES =====================
const unidadesContent = [
  '<div class="page-header">',
  '  <div><h1>Gestion de Unidades</h1><p>Registro y control de buses del sistema</p></div>',
  '  <button class="btn btn-primary" onclick="abrirModal()">+ Nueva Unidad</button>',
  '</div>',
  '<div class="stats-grid" style="grid-template-columns:repeat(4,1fr)">',
  '  <div class="stat-card"><div class="stat-icon azul">&#x1F68C;</div><div><div class="stat-value" id="stT">0</div><div class="stat-label">Total</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon verde">&#x2705;</div><div><div class="stat-value" id="stS">0</div><div class="stat-label">En Servicio</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon naranja">&#x1F527;</div><div><div class="stat-value" id="stM">0</div><div class="stat-label">Mantenimiento</div></div></div>',
  '  <div class="stat-card"><div class="stat-icon rojo">&#x274C;</div><div><div class="stat-value" id="stF">0</div><div class="stat-label">Fuera Servicio</div></div></div>',
  '</div>',
  '<div class="card">',
  '  <div class="card-header">',
  '    <h3>Lista de Unidades</h3>',
  '    <div class="search-bar" style="margin:0">',
  '      <input type="text" class="search-input" id="searchInput" placeholder="Buscar por numero, placa, modelo..." oninput="filtrar(this.value)" style="min-width:280px">',
  '      <select class="form-control" id="filterEstado" onchange="filtrar()" style="width:auto">',
  '        <option value="">Todos los estados</option>',
  '        <option value="en_servicio">En Servicio</option>',
  '        <option value="en_mantenimiento">En Mantenimiento</option>',
  '        <option value="fuera_de_servicio">Fuera de Servicio</option>',
  '      </select>',
  '    </div>',
  '  </div>',
  '  <div class="card-body">',
  '    <div class="table-wrap"><table>',
  '      <thead><tr><th>No.</th><th>Numero</th><th>Placa</th><th>Modelo</th><th>Año</th><th>Capacidad</th><th>Conductor</th><th>Estado</th><th>Acciones</th></tr></thead>',
  '      <tbody id="tbUnidades"><tr><td colspan="9" class="loading"><div class="spinner"></div></td></tr></tbody>',
  '    </table></div>',
  '  </div>',
  '</div>',
  '<div class="modal-overlay" id="modalOverlay">',
  '  <div class="modal"><div class="modal-header"><h3 id="modalTitle">Nueva Unidad</h3><button class="modal-close" onclick="cerrarModal()">x</button></div>',
  '  <div class="modal-body">',
  '    <input type="hidden" id="editId">',
  '    <div class="form-grid">',
  '      <div class="form-group"><label class="form-label">Numero de Unidad *</label><input class="form-control" id="fNumero" placeholder="BRT-001" required></div>',
  '      <div class="form-group"><label class="form-label">Placa</label><input class="form-control" id="fPlaca" placeholder="GTM-001"></div>',
  '      <div class="form-group"><label class="form-label">Modelo</label><input class="form-control" id="fModelo" placeholder="Volvo 7900"></div>',
  '      <div class="form-group"><label class="form-label">Año</label><input class="form-control" type="number" id="fAnio" placeholder="2024"></div>',
  '      <div class="form-group"><label class="form-label">Capacidad</label><input class="form-control" type="number" id="fCapacidad" value="80"></div>',
  '      <div class="form-group"><label class="form-label">Estado</label><select class="form-control" id="fEstado"><option value="en_servicio">En Servicio</option><option value="en_mantenimiento">En Mantenimiento</option><option value="fuera_de_servicio">Fuera de Servicio</option></select></div>',
  '    </div>',
  '  </div>',
  '  <div class="modal-footer"><button class="btn btn-secondary" onclick="cerrarModal()">Cancelar</button><button class="btn btn-primary" onclick="guardar()">Guardar</button></div>',
  '  </div>',
  '</div>',
  '<script>',
  'var unidades=[];',
  'async function cargar(){',
  '  try{',
  '    var d=await api.get("/unidades/estadisticas");',
  '    document.getElementById("stT").textContent=d.total||0;',
  '    document.getElementById("stS").textContent=d.en_servicio||0;',
  '    document.getElementById("stM").textContent=d.en_mantenimiento||0;',
  '    document.getElementById("stF").textContent=d.fuera_servicio||0;',
  '  }catch(e){}',
  '  try{',
  '    unidades=await api.get("/unidades");',
  '    renderTabla(unidades);',
  '  }catch(e){document.getElementById("tbUnidades").innerHTML="<tr><td colspan=9 style=\'text-align:center;color:red\'>Error al cargar</td></tr>";}',
  '}',
  'function renderTabla(data){',
  '  var tb=document.getElementById("tbUnidades");',
  '  if(!data.length){tb.innerHTML="<tr><td colspan=9 style=\'text-align:center;padding:30px;color:#9ca3af\'>No hay unidades registradas</td></tr>";return;}',
  '  tb.innerHTML=data.map(function(u,i){',
  '    var conductor=u.conductor_nombre?u.conductor_nombre+" "+u.conductor_apellido:"<span style=\'color:#9ca3af\'>Sin asignar</span>";',
  '    var estadoBadge=badgeEstadoUnidad(u.estado);',
  '    return "<tr><td>"+(i+1)+"</td><td><strong>"+u.numero+"</strong></td><td>"+(u.placa||"-")+"</td><td>"+(u.modelo||"-")+"</td><td>"+(u.anio||"-")+"</td><td>"+(u.capacidad||"-")+"</td><td>"+conductor+"</td><td>"+estadoBadge+"</td><td><div style=\'display:flex;gap:6px\'><button class=\'btn btn-sm btn-outline\' onclick=\'editar("+u.id+")\'>Editar</button><button class=\'btn btn-sm btn-danger\' onclick=\'eliminar("+u.id+")\'>Eliminar</button></div></td></tr>";',
  '  }).join("");',
  '}',
  'function filtrar(val){',
  '  var q=(val||document.getElementById("searchInput").value).toLowerCase();',
  '  var e=document.getElementById("filterEstado").value;',
  '  var f=unidades.filter(function(u){',
  '    var match=!q||(u.numero||"").toLowerCase().includes(q)||(u.placa||"").toLowerCase().includes(q)||(u.modelo||"").toLowerCase().includes(q);',
  '    var stMatch=!e||u.estado===e;',
  '    return match&&stMatch;',
  '  });',
  '  renderTabla(f);',
  '}',
  'function abrirModal(data){',
  '  document.getElementById("modalTitle").textContent=data?"Editar Unidad":"Nueva Unidad";',
  '  document.getElementById("editId").value=data?data.id:"";',
  '  document.getElementById("fNumero").value=data?data.numero:"";',
  '  document.getElementById("fPlaca").value=data?data.placa:"";',
  '  document.getElementById("fModelo").value=data?data.modelo:"";',
  '  document.getElementById("fAnio").value=data?data.anio:"";',
  '  document.getElementById("fCapacidad").value=data?data.capacidad:80;',
  '  document.getElementById("fEstado").value=data?data.estado:"en_servicio";',
  '  document.getElementById("modalOverlay").classList.add("active");',
  '}',
  'function cerrarModal(){document.getElementById("modalOverlay").classList.remove("active");}',
  'async function editar(id){var u=unidades.find(function(x){return x.id===id;});if(u)abrirModal(u);}',
  'async function guardar(){',
  '  var id=document.getElementById("editId").value;',
  '  var data={numero:document.getElementById("fNumero").value,placa:document.getElementById("fPlaca").value,modelo:document.getElementById("fModelo").value,anio:document.getElementById("fAnio").value,capacidad:document.getElementById("fCapacidad").value,estado:document.getElementById("fEstado").value};',
  '  try{',
  '    if(id)await api.put("/unidades/"+id,data); else await api.post("/unidades",data);',
  '    toast(id?"Unidad actualizada":"Unidad registrada","success");',
  '    cerrarModal();cargar();',
  '  }catch(e){toast(e.message,"error");}',
  '}',
  'async function eliminar(id){',
  '  if(!confirm("Eliminar esta unidad?"))return;',
  '  try{await api.del("/unidades/"+id);toast("Unidad eliminada","success");cargar();}catch(e){toast(e.message,"error");}',
  '}',
  'cargar();',
  '</script>'
].join('\n');

fs.writeFileSync(base + '/unidades.html', page('Unidades', 'unidades', unidadesContent), 'utf8');
console.log('unidades.html written');

// ===================== CONDUCTORES =====================
const conductoresContent = [
  '<div class="page-header">',
  '  <div><h1>Conductores</h1><p>Gestion de conductores del sistema</p></div>',
  '  <button class="btn btn-primary" onclick="abrirModal()">+ Nuevo Conductor</button>',
  '</div>',
  '<div class="card">',
  '  <div class="card-header">',
  '    <h3>Lista de Conductores</h3>',
  '    <div class="search-bar" style="margin:0">',
  '      <input type="text" class="search-input" id="searchInput" placeholder="Buscar por nombre, DPI, licencia..." oninput="filtrar(this.value)" style="min-width:280px">',
  '      <select class="form-control" id="filterEstado" onchange="filtrar()" style="width:auto">',
  '        <option value="">Todos</option><option value="activo">Activos</option><option value="inactivo">Inactivos</option>',
  '      </select>',
  '    </div>',
  '  </div>',
  '  <div class="card-body"><div class="table-wrap"><table>',
  '    <thead><tr><th>No.</th><th>Nombre</th><th>DPI</th><th>Licencia</th><th>Telefono</th><th>Unidad</th><th>Estado</th><th>Acciones</th></tr></thead>',
  '    <tbody id="tbConductores"><tr><td colspan="8" class="loading"><div class="spinner"></div></td></tr></tbody>',
  '  </table></div></div>',
  '</div>',
  '<div class="modal-overlay" id="modalOverlay">',
  '  <div class="modal"><div class="modal-header"><h3 id="modalTitle">Nuevo Conductor</h3><button class="modal-close" onclick="cerrarModal()">x</button></div>',
  '  <div class="modal-body">',
  '    <input type="hidden" id="editId">',
  '    <div class="form-grid">',
  '      <div class="form-group"><label class="form-label">Nombre *</label><input class="form-control" id="fNombre" required></div>',
  '      <div class="form-group"><label class="form-label">Apellido *</label><input class="form-control" id="fApellido" required></div>',
  '      <div class="form-group"><label class="form-label">DPI</label><input class="form-control" id="fDpi"></div>',
  '      <div class="form-group"><label class="form-label">Licencia</label><input class="form-control" id="fLicencia"></div>',
  '      <div class="form-group"><label class="form-label">Telefono</label><input class="form-control" id="fTelefono"></div>',
  '      <div class="form-group"><label class="form-label">Email</label><input class="form-control" type="email" id="fEmail"></div>',
  '      <div class="form-group"><label class="form-label">Estado</label><select class="form-control" id="fEstado"><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></div>',
  '    </div>',
  '  </div>',
  '  <div class="modal-footer"><button class="btn btn-secondary" onclick="cerrarModal()">Cancelar</button><button class="btn btn-primary" onclick="guardar()">Guardar</button></div>',
  '  </div>',
  '</div>',
  '<script>',
  'var conductores=[];',
  'async function cargar(){',
  '  try{conductores=await api.get("/conductores");renderTabla(conductores);}catch(e){}',
  '}',
  'function renderTabla(data){',
  '  var tb=document.getElementById("tbConductores");',
  '  if(!data.length){tb.innerHTML="<tr><td colspan=8 style=\'text-align:center;padding:30px;color:#9ca3af\'>No hay conductores</td></tr>";return;}',
  '  tb.innerHTML=data.map(function(c,i){',
  '    return "<tr><td>"+(i+1)+"</td><td><strong>"+c.nombre+" "+c.apellido+"</strong></td><td>"+(c.dpi||"-")+"</td><td>"+(c.licencia||"-")+"</td><td>"+(c.telefono||"-")+"</td><td>"+(c.unidad_numero||"<span style=\'color:#9ca3af\'>Sin asignar</span>")+"</td><td>"+badgeEstadoConductor(c.estado)+"</td><td><div style=\'display:flex;gap:6px\'><button class=\'btn btn-sm btn-outline\' onclick=\'editar("+c.id+")\'>Editar</button><button class=\'btn btn-sm btn-danger\' onclick=\'eliminar("+c.id+")\'>Eliminar</button></div></td></tr>";',
  '  }).join("");',
  '}',
  'function filtrar(){',
  '  var q=document.getElementById("searchInput").value.toLowerCase();',
  '  var e=document.getElementById("filterEstado").value;',
  '  renderTabla(conductores.filter(function(c){',
  '    return(!q||(c.nombre+" "+c.apellido+" "+c.dpi+" "+c.licencia).toLowerCase().includes(q))&&(!e||c.estado===e);',
  '  }));',
  '}',
  'function abrirModal(d){',
  '  document.getElementById("modalTitle").textContent=d?"Editar Conductor":"Nuevo Conductor";',
  '  ["editId","fNombre","fApellido","fDpi","fLicencia","fTelefono","fEmail"].forEach(function(id){document.getElementById(id).value="";});',
  '  if(d){document.getElementById("editId").value=d.id;document.getElementById("fNombre").value=d.nombre;document.getElementById("fApellido").value=d.apellido;document.getElementById("fDpi").value=d.dpi||"";document.getElementById("fLicencia").value=d.licencia||"";document.getElementById("fTelefono").value=d.telefono||"";document.getElementById("fEmail").value=d.email||"";document.getElementById("fEstado").value=d.estado;}',
  '  document.getElementById("modalOverlay").classList.add("active");',
  '}',
  'function cerrarModal(){document.getElementById("modalOverlay").classList.remove("active");}',
  'function editar(id){var c=conductores.find(function(x){return x.id===id;});if(c)abrirModal(c);}',
  'async function guardar(){',
  '  var id=document.getElementById("editId").value;',
  '  var data={nombre:document.getElementById("fNombre").value,apellido:document.getElementById("fApellido").value,dpi:document.getElementById("fDpi").value,licencia:document.getElementById("fLicencia").value,telefono:document.getElementById("fTelefono").value,email:document.getElementById("fEmail").value,estado:document.getElementById("fEstado").value};',
  '  try{if(id)await api.put("/conductores/"+id,data);else await api.post("/conductores",data);toast(id?"Conductor actualizado":"Conductor registrado","success");cerrarModal();cargar();}catch(e){toast(e.message,"error");}',
  '}',
  'async function eliminar(id){if(!confirm("Eliminar conductor?"))return;try{await api.del("/conductores/"+id);toast("Conductor eliminado","success");cargar();}catch(e){toast(e.message,"error");}}',
  'cargar();',
  '</script>'
].join('\n');

fs.writeFileSync(base + '/conductores.html', page('Conductores', 'conductores', conductoresContent), 'utf8');
console.log('conductores.html written');

// ===================== ASIGNACIONES =====================
const asignacionesContent = [
  '<div class="page-header">',
  '  <div><h1>Asignaciones</h1><p>Asignacion de buses y conductores a rutas</p></div>',
  '  <button class="btn btn-primary" onclick="abrirModal()">+ Nueva Asignacion</button>',
  '</div>',
  '<div class="card"><div class="card-header"><h3>Lista de Asignaciones</h3></div>',
  '  <div class="card-body"><div class="table-wrap"><table>',
  '    <thead><tr><th>No.</th><th>Unidad</th><th>Ruta</th><th>Conductor</th><th>Fecha Inicio</th><th>Fecha Fin</th><th>Estado</th><th>Acciones</th></tr></thead>',
  '    <tbody id="tbAsig"><tr><td colspan="8" class="loading"><div class="spinner"></div></td></tr></tbody>',
  '  </table></div></div>',
  '</div>',
  '<div class="modal-overlay" id="modalOverlay">',
  '  <div class="modal"><div class="modal-header"><h3 id="modalTitle">Nueva Asignacion</h3><button class="modal-close" onclick="cerrarModal()">x</button></div>',
  '  <div class="modal-body">',
  '    <input type="hidden" id="editId">',
  '    <div class="form-group"><label class="form-label">Unidad *</label><select class="form-control" id="fUnidad"></select></div>',
  '    <div class="form-group"><label class="form-label">Ruta *</label><select class="form-control" id="fRuta"></select></div>',
  '    <div class="form-group"><label class="form-label">Conductor *</label><select class="form-control" id="fConductor"></select></div>',
  '    <div class="form-grid">',
  '      <div class="form-group"><label class="form-label">Fecha Inicio *</label><input type="date" class="form-control" id="fFechaInicio"></div>',
  '      <div class="form-group"><label class="form-label">Fecha Fin</label><input type="date" class="form-control" id="fFechaFin"></div>',
  '    </div>',
  '    <div class="form-group"><label class="form-label">Estado</label><select class="form-control" id="fEstado"><option value="activa">Activa</option><option value="inactiva">Inactiva</option></select></div>',
  '  </div>',
  '  <div class="modal-footer"><button class="btn btn-secondary" onclick="cerrarModal()">Cancelar</button><button class="btn btn-primary" onclick="guardar()">Guardar</button></div>',
  '  </div>',
  '</div>',
  '<script>',
  'var asigs=[];',
  'async function cargar(){',
  '  try{asigs=await api.get("/asignaciones");',
  '    var tb=document.getElementById("tbAsig");',
  '    if(!asigs.length){tb.innerHTML="<tr><td colspan=8 style=\'text-align:center;padding:30px;color:#9ca3af\'>No hay asignaciones</td></tr>";return;}',
  '    tb.innerHTML=asigs.map(function(a,i){',
  '      return "<tr><td>"+(i+1)+"</td><td><strong>"+a.unidad_numero+"</strong></td><td>"+a.ruta_nombre+"</td><td>"+a.conductor_nombre+" "+a.conductor_apellido+"</td><td>"+(a.fecha_inicio||"-")+"</td><td>"+(a.fecha_fin||"Indefinida")+"</td><td>"+(a.estado==="activa"?"<span class=\'badge badge-success\'>Activa</span>":"<span class=\'badge badge-secondary\'>Inactiva</span>")+"</td><td><div style=\'display:flex;gap:6px\'><button class=\'btn btn-sm btn-outline\' onclick=\'editar("+a.id+")\'>Editar</button><button class=\'btn btn-sm btn-danger\' onclick=\'eliminar("+a.id+")\'>Eliminar</button></div></td></tr>";',
  '    }).join("");',
  '  }catch(e){}',
  '}',
  'async function abrirModal(d){',
  '  document.getElementById("modalTitle").textContent=d?"Editar Asignacion":"Nueva Asignacion";',
  '  document.getElementById("editId").value=d?d.id:"";',
  '  var [unidades,rutas,conductores]=await Promise.all([api.get("/unidades"),api.get("/rutas"),api.get("/conductores")]);',
  '  var selU=document.getElementById("fUnidad");selU.innerHTML=unidades.filter(function(u){return u.estado==="en_servicio";}).map(function(u){return"<option value="+u.id+(d&&d.unidad_id===u.id?" selected":"")+">"+u.numero+" - "+u.placa+"</option>";}).join("");',
  '  var selR=document.getElementById("fRuta");selR.innerHTML=rutas.map(function(r){return"<option value="+r.id+(d&&d.ruta_id===r.id?" selected":"")+">"+r.nombre+"</option>";}).join("");',
  '  var selC=document.getElementById("fConductor");selC.innerHTML=conductores.filter(function(c){return c.estado==="activo";}).map(function(c){return"<option value="+c.id+(d&&d.conductor_id===c.id?" selected":"")+">"+c.nombre+" "+c.apellido+"</option>";}).join("");',
  '  document.getElementById("fFechaInicio").value=d?d.fecha_inicio:"";',
  '  document.getElementById("fFechaFin").value=d?d.fecha_fin||"":"";',
  '  if(d)document.getElementById("fEstado").value=d.estado;',
  '  document.getElementById("modalOverlay").classList.add("active");',
  '}',
  'function cerrarModal(){document.getElementById("modalOverlay").classList.remove("active");}',
  'function editar(id){var a=asigs.find(function(x){return x.id===id;});if(a)abrirModal(a);}',
  'async function guardar(){',
  '  var id=document.getElementById("editId").value;',
  '  var data={unidad_id:document.getElementById("fUnidad").value,ruta_id:document.getElementById("fRuta").value,conductor_id:document.getElementById("fConductor").value,fecha_inicio:document.getElementById("fFechaInicio").value,fecha_fin:document.getElementById("fFechaFin").value||null,estado:document.getElementById("fEstado").value};',
  '  try{if(id)await api.put("/asignaciones/"+id,data);else await api.post("/asignaciones",data);toast(id?"Asignacion actualizada":"Asignacion creada","success");cerrarModal();cargar();}catch(e){toast(e.message,"error");}',
  '}',
  'async function eliminar(id){if(!confirm("Eliminar asignacion?"))return;try{await api.del("/asignaciones/"+id);toast("Eliminada","success");cargar();}catch(e){toast(e.message,"error");}}',
  'cargar();',
  '</script>'
].join('\n');

fs.writeFileSync(base + '/asignaciones.html', page('Asignaciones', 'asignaciones', asignacionesContent), 'utf8');
console.log('asignaciones.html written');

console.log('All HTML pages created!');
